server:
  port: 8077
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g130mainserver
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}


keycloak:
  url: http://localhost:8000
  realm: bitlab-realm
  client: bitlab-user-service-client
  client-secret: pbVj0h3Bi1MDB8IwddJfCd0SyzSYth6i
  username: bitlab_admin
  password: qweqwe
  grant-type: password

minio:
  url: http://localhost:9000
  user: root
  password: Minio_Java_Middle_2024
  bucket: dev-bucket