-- liquibase formatted sql

-- changeset alisher:1
-- comment создаю базу
CREATE TABLE IF NOT EXISTS courses
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

-- changeset magzhan:2
CREATE TABLE chapters (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ORDER_NUM INT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT chapter_courses FOREIGN KEY (COURSE_ID) REFERENCES courses(ID) ON DELETE CASCADE
);

-- changeset magzhan:3
CREATE TABLE lessons (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CONTENT TEXT,
    ORDER_NUM INT NOT NULL,
    CHAPTER_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT lesson_chapters FOREIGN KEY (CHAPTER_ID) REFERENCES chapters(ID) ON DELETE CASCADE
);