-- liquibase formatted sql

-- changeset alisher:1
-- comment создаю базу
CREATE TABLE IF NOT EXISTS coursesEnglish
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

-- changeset magzhan:2
CREATE TABLE chapters (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ORDER_NUM INT NOT NULL,
    COURSE_ENGLISH_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT chapter_courses FOREIGN KEY (COURSE_ENGLISH_ID) REFERENCES coursesEnglish(id) ON DELETE CASCADE
);

-- changeset magzhan:3
CREATE TABLE lessons (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CONTENT TEXT,
    ORDER_NUM INT NOT NULL,
    CHAPTER_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT lesson_chapters FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE
);