-- liquibase formatted sql

-- changeset alisher:1
-- comment создаю базу
CREATE TABLE IF NOT EXISTS courseEnglish
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP
);

-- changeset magzhan:2
CREATE TABLE chapter (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ORDER_NUM INT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT chapter_course FOREIGN KEY (course_id) REFERENCES courseEnglish(id) ON DELETE CASCADE
);

-- changeset magzhan:3
CREATE TABLE lesson (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CONTENT TEXT,
    ORDER_NUM INT NOT NULL,
    CHAPTER_ID BIGINT NOT NULL,
    CREATED_TIME TIMESTAMP,
    UPDATED_TIME TIMESTAMP,
    CONSTRAINT lesson_chapter FOREIGN KEY (chapter_id) REFERENCES chapter(id) ON DELETE CASCADE
);