services:
  backend:
    image: 'mainservice'
    container_name: back
    depends_on:
      - database
      - minio-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    ports:
      - "8088:8077"

  database:
    image: 'postgres'
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - "4567:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5434:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    depends_on:
      - keycloak-db
    environment:
      - KC_HTTP_RELATIVE_PATH=/
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8000:8080"

  minio-service:
    image: quay.io/minio/minio
    container_name: minio_service_container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Minio_Java_Middle_2024
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    depends_on:
      - minio-service
    environment:
      MC_HOST: http://root:Minio_Java_Middle_2024@minio-service:9000
    entrypoint: >
      /bin/sh -c "
      echo Starting Minio setup...;
      mc alias set minio http://minio-service:9000 root Minio_Java_Middle_2024;
      mc mb minio/dev-bucket;
      exit 0;
      "

volumes:
  postgres_data:
  keycloak_data:
  minio_data:
